import { ISlideShowCarouselData } from '../../../components/slideShow/interfaces';

const newsItems : Array<ISlideShowCarouselData> = [
 {
   ID : 1,
   DisplayName : 'News Item 1',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL : '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 1 Description',
   DWNewsThumbnailImage : 'http://candidbelle.com/wp-content/uploads/2013/05/shutterstock_72655096-156x156.jpg',
   DWNewsImage : 'http://candidbelle.com/wp-content/uploads/2013/05/shutterstock_72655096-156x156.jpg',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 },
 {
   ID : 2,
   DisplayName : 'News Item 2',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL: '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 2 Description',
   DWNewsThumbnailImage : 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQvZ2egrSBAcPrZEKLnnYV5vpJAliJWEknTa4MSUqUyjZ2FccBH',
   DWNewsImage : 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQvZ2egrSBAcPrZEKLnnYV5vpJAliJWEknTa4MSUqUyjZ2FccBH',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 },
 {
   ID : 3,
   DisplayName : 'News Item 3',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL : '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 3 Description',
   DWNewsThumbnailImage : 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSKJtMHCMI2494egbif7gqtmSXTrUJiH5Jd8k88_oJv0WcEvOf2',
   DWNewsImage : 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSKJtMHCMI2494egbif7gqtmSXTrUJiH5Jd8k88_oJv0WcEvOf2',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 },
 {
   ID : 4,
   DisplayName : 'News Item 4',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL: '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 4 Description',
   DWNewsThumbnailImage : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3BGkQZ4LGI0F15z_a7kFalrWeaQWoPHHpFGIc4YXqWNNleLzHqw',
   DWNewsImage : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3BGkQZ4LGI0F15z_a7kFalrWeaQWoPHHpFGIc4YXqWNNleLzHqw',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 },
 {
   ID : 5,
   DisplayName : 'News Item 5',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL : '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 5 Description',
   DWNewsThumbnailImage : 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcREIdK5Ivv4lurMET5HcWdns1u8kAdmRw0gIZClk6T1A2SYr1MpYw',
   DWNewsImage : 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcREIdK5Ivv4lurMET5HcWdns1u8kAdmRw0gIZClk6T1A2SYr1MpYw',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 },
 {
   ID : 6,
   DisplayName : 'News Item 6',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL: '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 6 Description',
   DWNewsThumbnailImage : 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSAcjbYGdBynaJpu3f-wVaXoDqUmOxW_pwqPvG4wSY_UnbBRZEsEg',
   DWNewsImage : 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSAcjbYGdBynaJpu3f-wVaXoDqUmOxW_pwqPvG4wSY_UnbBRZEsEg',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 },
 {
   ID : 7,
   DisplayName : 'News Item 7',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL : '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 7 Description',
   DWNewsThumbnailImage : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqd_RhZaWE4YIAC3TkgmeGV5CI6IPCzJ8u4x8Rl1f_Sa0GpBjY',
   DWNewsImage : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqd_RhZaWE4YIAC3TkgmeGV5CI6IPCzJ8u4x8Rl1f_Sa0GpBjY',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 },
 {
   ID : 8,
   DisplayName : 'News Item 8',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL: '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 8 Description',
   DWNewsThumbnailImage : 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRhP3-PN-bgRZSnDzkLlQQaSio99l9TLwfssSITjaZJ2qsly9sGcw',
   DWNewsImage : 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRhP3-PN-bgRZSnDzkLlQQaSio99l9TLwfssSITjaZJ2qsly9sGcw',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 },
 {
   ID : 9,
   DisplayName : 'News Item 9',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL : '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 9 Description',
   DWNewsThumbnailImage : 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSLfQi1KvlIM1QHTeD9NCKEMa7KRfQyiTTRfvq8R92lJcn2E8Q3yQ',
   DWNewsImage : 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSLfQi1KvlIM1QHTeD9NCKEMa7KRfQyiTTRfvq8R92lJcn2E8Q3yQ',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 },
 {
   ID : 10,
   DisplayName : 'News Item 10',
   Modified : new Date().toDateString(),
   DWAUTBusinessStructure : [],
   DWAUTLocation : [],
   DWPublishedDate : new Date().toDateString(),
   DWExpiryDate : new Date().toDateString(),
   DWLink : { URL: '', Description : ''},
   DWIsFeatured : true,
   DWNewsShortdesc : 'News Item 10 Description',
   DWNewsThumbnailImage : 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTworMJD9vdBHZ2YhHMXnbfqd0mTPsv84mo5DBIiyN5wMZgcCGn',
   DWNewsImage : 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTworMJD9vdBHZ2YhHMXnbfqd0mTPsv84mo5DBIiyN5wMZgcCGn',
   OriginalPath : '',
   DWTitle : '',
   likesCount : 0,
   commentsCount : 0
 }    
];

export default newsItems;